name: Deploy PWA
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - run: npm install -g @bubblewrap/cli
      - run: bubblewrap update --jdkPath=echo $JAVA_HOME
