name: Deploy PWA
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: malinskiy/action-android/install-sdk@release/0.1.2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          java-package: jdk
          architecture: x64
      - run: npm install -g @bubblewrap/cli
      - run: sdkmanager platform-tools
      - run: echo $ANDROID_HOME
      - run: echo $JAVA_HOME
      - run: bubblewrap updateConfig --jdkPath=$JAVA_HOME --androidSdkPath=$ANDROID_HOME
      - run: cat ~/.bubblewrap/config.json
      - run: bubblewrap update 
